scrape_configs:
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'bit-hedge-promethues'
    scrape_interval: 5s # for demo purpose
    static_configs:
      - targets: ['bit-hedge:8401']
