scrape_configs:
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'corona-weg-promethues'
    scrape_interval: 10m
    static_configs:
      - targets: ['corona-weg:8404']
